version: 0.2

phases:
  install: 
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - cd client && npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build s3://jp-node-build